---
- name: write all release data into a single file
  shell: cat /etc/*-release > release.info.dat

- name: fetch release data between remotes
  fetch: 
    src: ~/release.info.dat
    dest: ./.var 
    
- name: fetch cpuinfo
  fetch:
    src: /proc/cpuinfo
    dest: ./var

- name: fetch meminfo
  fetch:
    src: /proc/meminfo
    dest: ./var